name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jekyll-build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # 현재 가장 안정적인 버전
          bundler-cache: false # 캐시 충돌 방지를 위해 잠시 끔

      - name: Bundle Install
        run: |
          bundle config set --local frozen false
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production